### ISSUE TITLE
Question about console log

### ISSUE THREAD

**Issue by McCarrick111** [Insane-96/GalaxiteMod#3]
Hi there, my name is John.

So I've just added Galaxite to a custom modpack on our server. I'm noticing that my  console log is totally filled with the following command line;

> 10.02 23:54:16 [Server] Server thread/INFO [STDOUT]: [net.insane96mcp.galaxite.capabilities.PlayerDataStorage:writeNBT:18]: Writing: {}

Now this has NOT been causing me any sort of issues as far as I am aware, however along with Galaxite this last update was fairly substantial and added a ton of new mods. Since the update we've been having more lag issues on the server - nothing world shattering but noticeable.

So my question is this - does this function lag a server given its frequency, and if so is there a way in the configs to reduce how often it runs this command? I'm not accusing so much as checking in since I suspect it is far more likely another mod (or multiple) that have contributed to the increase in lag.

Thank you for your time, creative mod!

**Comment by Insane96** [comment]
First off, that is a bug. It wasn't meant to be in the release.

Second, this function (console log) can cause lag in servers (and SP too) if spammed very often, like every tick (like 20 times per second) but iirc mine is executed about once every 30 seconds so it shouldn't cause any lag.

Thanks for repeporting btw

**Comment by McCarrick111** [comment]
Understandable, happy to report it!

Is there any way I can reduce the executions? It seems to run it as you said, maybe every 30 seconds or so - I cannot tell if its running for each player independently however. 

I assume that this isn't causing the lag, but if I could manually reduce the executions I could at least test it and see if it is contributing to it. Thanks for the swift reply!

**Comment by Insane96** [comment]
There's no way :(

I'll fix it ASAP and release a 1.0.1 version

**Comment by McCarrick111** [comment]
Fantastic! No rush on my account - we're doing just fine. :)

Thank you so much for your help!

**Comment by Insane96** [comment]
Forgot
Fixed with https://github.com/Insane-96/GalaxiteMod/commit/a7f779288ae885adc967db8af131480f83cf609b

**Comment by McCarrick111** [comment]
Great, thanks!
