### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Insane96** [Insane-96/GalaxiteMod#4]
When editing .lang files, please don't remove `%x` and `§x` (if any)
Those are used respectively for in-code values and for color

- [x] Italian (me)
- [ ] German
- [ ] Spanish (#8) (needs update)
- [ ] French
- [ ] Russian (#7) (needs update)
- [ ] Greek
- [ ] Korean
- [ ] Japanese
- [ ] Chinese (Simplified)
- [ ] Chinese (Traditional)

How to do it:
- Copy the text from en_US.lang
- Get here: https://github.com/Insane-96/GalaxiteMod/tree/master/resources/assets/galaxite/lang
- Press _Create New File_
- Name your file according to the translation language, check here: https://minecraft.gamepedia.com/Language#Available_languages
- Paste and edit the strings after the = (equal) and do not put spaces between them. Remember to not touch %x and §x
- On the bottom of the page make sure _Create a new branch for this commit and start a pull request._ is selected and press _Propose New File_
- Press _Create pull request_

**Comment by CobaltRealm** [comment]
Hi!

I would like to help with translating to Spanish, but I'm a little noob with github so can you explain me how to do it?

**Comment by Insane96** [comment]
Updated the first comment with How To

**Comment by Aer-ink** [comment]
I'm not sure if I did it right but there should be another spanish (mexico) translation

**Comment by LonelyStarGit** [comment]
Hi i'd offer to translate the mod to german, but i literally just made this account and have never used Github before, would you mind just sending me the file via discord or something?^^
my tag is Lonely Star#6056
